### ISSUE TITLE
Failed to activate the atom-slide-show package

### ISSUE THREAD

**Issue by Elia0107** [rk0der/atom-slide-show#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [atom-slide-show](https://github.com/rk0der/atom-slide-show) package 0.3.0

### Stack Trace

Failed to activate the atom-slide-show package

```
At Command failed: ls -d C:\Users\utente\Pictures\Viaggi-Image\Tutte\
"ls" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.


Error: Command failed: ls -d C:\Users\utente\Pictures\Viaggi-Image\Tutte\
"ls" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

    at checkExecSyncError (child_process.js:502:13)
    at execSync (child_process.js:542:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at Main.start_iteration (/packages/atom-slide-show/lib/main.js:56:19)
    at Main.toggle (/packages/atom-slide-show/lib/main.js:45:12)
    at Main.activate (/packages/atom-slide-show/lib/main.js:26:12)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:690:42)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -3:05.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -2:34.3.0 settings-view:uninstall-packages (input.hidden-input)
     -1:41.9.0 expose:toggle (div.panels-item)
     -0:39.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-i18n 0.12.0 
atom-ide-ui 0.5.0 
atom-slide-show 0.3.0 
autocomplete-glsl 0.2.3 
autocomplete-paths 2.12.0 
autocomplete-webgl 1.1.0 
expose 0.15.0 
file-icons 2.1.12 
highlight-line 0.12.0 
highlight-selected 0.13.1 
ide-typescript 0.6.1 
indent-guide-improved 1.4.13 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
Zen 0.18.0 
```

**Comment by octarect** [comment]
Thanks for your report.

This package have not supported for Windows yet.  
The error you meant is caused by differences of ls option between Unix and Windows.  

I think it should not be implemented by calling command in each OS.

**Comment by Elia0107** [comment]
You will add support for Windows?
